/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/messages.pb-c.h"
void   generic_message__init
                     (GenericMessage         *message)
{
  static GenericMessage init_value = GENERIC_MESSAGE__INIT;
  *message = init_value;
}
size_t generic_message__get_packed_size
                     (const GenericMessage *message)
{
  assert(message->base.descriptor == &generic_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t generic_message__pack
                     (const GenericMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &generic_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t generic_message__pack_to_buffer
                     (const GenericMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &generic_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GenericMessage *
       generic_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GenericMessage *)
     protobuf_c_message_unpack (&generic_message__descriptor,
                                allocator, len, data);
}
void   generic_message__free_unpacked
                     (GenericMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &generic_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ephemeral__init
                     (Ephemeral         *message)
{
  static Ephemeral init_value = EPHEMERAL__INIT;
  *message = init_value;
}
size_t ephemeral__get_packed_size
                     (const Ephemeral *message)
{
  assert(message->base.descriptor == &ephemeral__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ephemeral__pack
                     (const Ephemeral *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ephemeral__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ephemeral__pack_to_buffer
                     (const Ephemeral *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ephemeral__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ephemeral *
       ephemeral__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ephemeral *)
     protobuf_c_message_unpack (&ephemeral__descriptor,
                                allocator, len, data);
}
void   ephemeral__free_unpacked
                     (Ephemeral *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ephemeral__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   text__init
                     (Text         *message)
{
  static Text init_value = TEXT__INIT;
  *message = init_value;
}
size_t text__get_packed_size
                     (const Text *message)
{
  assert(message->base.descriptor == &text__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t text__pack
                     (const Text *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &text__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t text__pack_to_buffer
                     (const Text *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &text__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Text *
       text__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Text *)
     protobuf_c_message_unpack (&text__descriptor,
                                allocator, len, data);
}
void   text__free_unpacked
                     (Text *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &text__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   knock__init
                     (Knock         *message)
{
  static Knock init_value = KNOCK__INIT;
  *message = init_value;
}
size_t knock__get_packed_size
                     (const Knock *message)
{
  assert(message->base.descriptor == &knock__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t knock__pack
                     (const Knock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &knock__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t knock__pack_to_buffer
                     (const Knock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &knock__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Knock *
       knock__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Knock *)
     protobuf_c_message_unpack (&knock__descriptor,
                                allocator, len, data);
}
void   knock__free_unpacked
                     (Knock *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &knock__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   link_preview__init
                     (LinkPreview         *message)
{
  static LinkPreview init_value = LINK_PREVIEW__INIT;
  *message = init_value;
}
size_t link_preview__get_packed_size
                     (const LinkPreview *message)
{
  assert(message->base.descriptor == &link_preview__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t link_preview__pack
                     (const LinkPreview *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &link_preview__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t link_preview__pack_to_buffer
                     (const LinkPreview *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &link_preview__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LinkPreview *
       link_preview__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LinkPreview *)
     protobuf_c_message_unpack (&link_preview__descriptor,
                                allocator, len, data);
}
void   link_preview__free_unpacked
                     (LinkPreview *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &link_preview__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tweet__init
                     (Tweet         *message)
{
  static Tweet init_value = TWEET__INIT;
  *message = init_value;
}
size_t tweet__get_packed_size
                     (const Tweet *message)
{
  assert(message->base.descriptor == &tweet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tweet__pack
                     (const Tweet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tweet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tweet__pack_to_buffer
                     (const Tweet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tweet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tweet *
       tweet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tweet *)
     protobuf_c_message_unpack (&tweet__descriptor,
                                allocator, len, data);
}
void   tweet__free_unpacked
                     (Tweet *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tweet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   article__init
                     (Article         *message)
{
  static Article init_value = ARTICLE__INIT;
  *message = init_value;
}
size_t article__get_packed_size
                     (const Article *message)
{
  assert(message->base.descriptor == &article__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t article__pack
                     (const Article *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &article__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t article__pack_to_buffer
                     (const Article *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &article__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Article *
       article__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Article *)
     protobuf_c_message_unpack (&article__descriptor,
                                allocator, len, data);
}
void   article__free_unpacked
                     (Article *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &article__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mention__init
                     (Mention         *message)
{
  static Mention init_value = MENTION__INIT;
  *message = init_value;
}
size_t mention__get_packed_size
                     (const Mention *message)
{
  assert(message->base.descriptor == &mention__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mention__pack
                     (const Mention *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mention__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mention__pack_to_buffer
                     (const Mention *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mention__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mention *
       mention__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mention *)
     protobuf_c_message_unpack (&mention__descriptor,
                                allocator, len, data);
}
void   mention__free_unpacked
                     (Mention *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mention__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   last_read__init
                     (LastRead         *message)
{
  static LastRead init_value = LAST_READ__INIT;
  *message = init_value;
}
size_t last_read__get_packed_size
                     (const LastRead *message)
{
  assert(message->base.descriptor == &last_read__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t last_read__pack
                     (const LastRead *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &last_read__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t last_read__pack_to_buffer
                     (const LastRead *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &last_read__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LastRead *
       last_read__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LastRead *)
     protobuf_c_message_unpack (&last_read__descriptor,
                                allocator, len, data);
}
void   last_read__free_unpacked
                     (LastRead *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &last_read__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cleared__init
                     (Cleared         *message)
{
  static Cleared init_value = CLEARED__INIT;
  *message = init_value;
}
size_t cleared__get_packed_size
                     (const Cleared *message)
{
  assert(message->base.descriptor == &cleared__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cleared__pack
                     (const Cleared *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cleared__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cleared__pack_to_buffer
                     (const Cleared *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cleared__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cleared *
       cleared__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cleared *)
     protobuf_c_message_unpack (&cleared__descriptor,
                                allocator, len, data);
}
void   cleared__free_unpacked
                     (Cleared *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cleared__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_hide__init
                     (MessageHide         *message)
{
  static MessageHide init_value = MESSAGE_HIDE__INIT;
  *message = init_value;
}
size_t message_hide__get_packed_size
                     (const MessageHide *message)
{
  assert(message->base.descriptor == &message_hide__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_hide__pack
                     (const MessageHide *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_hide__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_hide__pack_to_buffer
                     (const MessageHide *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_hide__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageHide *
       message_hide__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageHide *)
     protobuf_c_message_unpack (&message_hide__descriptor,
                                allocator, len, data);
}
void   message_hide__free_unpacked
                     (MessageHide *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &message_hide__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_delete__init
                     (MessageDelete         *message)
{
  static MessageDelete init_value = MESSAGE_DELETE__INIT;
  *message = init_value;
}
size_t message_delete__get_packed_size
                     (const MessageDelete *message)
{
  assert(message->base.descriptor == &message_delete__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_delete__pack
                     (const MessageDelete *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_delete__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_delete__pack_to_buffer
                     (const MessageDelete *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_delete__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageDelete *
       message_delete__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageDelete *)
     protobuf_c_message_unpack (&message_delete__descriptor,
                                allocator, len, data);
}
void   message_delete__free_unpacked
                     (MessageDelete *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &message_delete__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_edit__init
                     (MessageEdit         *message)
{
  static MessageEdit init_value = MESSAGE_EDIT__INIT;
  *message = init_value;
}
size_t message_edit__get_packed_size
                     (const MessageEdit *message)
{
  assert(message->base.descriptor == &message_edit__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_edit__pack
                     (const MessageEdit *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_edit__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_edit__pack_to_buffer
                     (const MessageEdit *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_edit__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageEdit *
       message_edit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageEdit *)
     protobuf_c_message_unpack (&message_edit__descriptor,
                                allocator, len, data);
}
void   message_edit__free_unpacked
                     (MessageEdit *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &message_edit__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   confirmation__init
                     (Confirmation         *message)
{
  static Confirmation init_value = CONFIRMATION__INIT;
  *message = init_value;
}
size_t confirmation__get_packed_size
                     (const Confirmation *message)
{
  assert(message->base.descriptor == &confirmation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t confirmation__pack
                     (const Confirmation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &confirmation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t confirmation__pack_to_buffer
                     (const Confirmation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &confirmation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Confirmation *
       confirmation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Confirmation *)
     protobuf_c_message_unpack (&confirmation__descriptor,
                                allocator, len, data);
}
void   confirmation__free_unpacked
                     (Confirmation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &confirmation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   location__init
                     (Location         *message)
{
  static Location init_value = LOCATION__INIT;
  *message = init_value;
}
size_t location__get_packed_size
                     (const Location *message)
{
  assert(message->base.descriptor == &location__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t location__pack
                     (const Location *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &location__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t location__pack_to_buffer
                     (const Location *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &location__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Location *
       location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Location *)
     protobuf_c_message_unpack (&location__descriptor,
                                allocator, len, data);
}
void   location__free_unpacked
                     (Location *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &location__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   image_asset__init
                     (ImageAsset         *message)
{
  static ImageAsset init_value = IMAGE_ASSET__INIT;
  *message = init_value;
}
size_t image_asset__get_packed_size
                     (const ImageAsset *message)
{
  assert(message->base.descriptor == &image_asset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t image_asset__pack
                     (const ImageAsset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &image_asset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t image_asset__pack_to_buffer
                     (const ImageAsset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &image_asset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ImageAsset *
       image_asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ImageAsset *)
     protobuf_c_message_unpack (&image_asset__descriptor,
                                allocator, len, data);
}
void   image_asset__free_unpacked
                     (ImageAsset *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &image_asset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   asset__original__init
                     (Asset__Original         *message)
{
  static Asset__Original init_value = ASSET__ORIGINAL__INIT;
  *message = init_value;
}
void   asset__preview__init
                     (Asset__Preview         *message)
{
  static Asset__Preview init_value = ASSET__PREVIEW__INIT;
  *message = init_value;
}
void   asset__image_meta_data__init
                     (Asset__ImageMetaData         *message)
{
  static Asset__ImageMetaData init_value = ASSET__IMAGE_META_DATA__INIT;
  *message = init_value;
}
void   asset__video_meta_data__init
                     (Asset__VideoMetaData         *message)
{
  static Asset__VideoMetaData init_value = ASSET__VIDEO_META_DATA__INIT;
  *message = init_value;
}
void   asset__audio_meta_data__init
                     (Asset__AudioMetaData         *message)
{
  static Asset__AudioMetaData init_value = ASSET__AUDIO_META_DATA__INIT;
  *message = init_value;
}
void   asset__remote_data__init
                     (Asset__RemoteData         *message)
{
  static Asset__RemoteData init_value = ASSET__REMOTE_DATA__INIT;
  *message = init_value;
}
void   asset__init
                     (Asset         *message)
{
  static Asset init_value = ASSET__INIT;
  *message = init_value;
}
size_t asset__get_packed_size
                     (const Asset *message)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t asset__pack
                     (const Asset *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t asset__pack_to_buffer
                     (const Asset *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &asset__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Asset *
       asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Asset *)
     protobuf_c_message_unpack (&asset__descriptor,
                                allocator, len, data);
}
void   asset__free_unpacked
                     (Asset *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &asset__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   external__init
                     (External         *message)
{
  static External init_value = EXTERNAL__INIT;
  *message = init_value;
}
size_t external__get_packed_size
                     (const External *message)
{
  assert(message->base.descriptor == &external__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external__pack
                     (const External *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external__pack_to_buffer
                     (const External *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
External *
       external__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (External *)
     protobuf_c_message_unpack (&external__descriptor,
                                allocator, len, data);
}
void   external__free_unpacked
                     (External *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &external__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reaction__init
                     (Reaction         *message)
{
  static Reaction init_value = REACTION__INIT;
  *message = init_value;
}
size_t reaction__get_packed_size
                     (const Reaction *message)
{
  assert(message->base.descriptor == &reaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reaction__pack
                     (const Reaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reaction__pack_to_buffer
                     (const Reaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Reaction *
       reaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Reaction *)
     protobuf_c_message_unpack (&reaction__descriptor,
                                allocator, len, data);
}
void   reaction__free_unpacked
                     (Reaction *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &reaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   calling__init
                     (Calling         *message)
{
  static Calling init_value = CALLING__INIT;
  *message = init_value;
}
size_t calling__get_packed_size
                     (const Calling *message)
{
  assert(message->base.descriptor == &calling__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t calling__pack
                     (const Calling *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &calling__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t calling__pack_to_buffer
                     (const Calling *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &calling__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Calling *
       calling__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Calling *)
     protobuf_c_message_unpack (&calling__descriptor,
                                allocator, len, data);
}
void   calling__free_unpacked
                     (Calling *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &calling__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor generic_message__field_descriptors[17] =
{
  {
    "message_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GenericMessage, message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, text),
    &text__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, image),
    &image_asset__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "knock",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, knock),
    &knock__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastRead",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, lastread),
    &last_read__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cleared",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, cleared),
    &cleared__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, external),
    &external__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clientAction",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, clientaction),
    &client_action__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "calling",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, calling),
    &calling__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "asset",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, asset),
    &asset__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hidden",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, hidden),
    &message_hide__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, location),
    &location__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deleted",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, deleted),
    &message_delete__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edited",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, edited),
    &message_edit__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confirmation",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, confirmation),
    &confirmation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reaction",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, reaction),
    &reaction__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ephemeral",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GenericMessage, content_case),
    offsetof(GenericMessage, ephemeral),
    &ephemeral__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned generic_message__field_indices_by_name[] = {
  9,   /* field[9] = asset */
  8,   /* field[8] = calling */
  5,   /* field[5] = cleared */
  7,   /* field[7] = clientAction */
  14,   /* field[14] = confirmation */
  12,   /* field[12] = deleted */
  13,   /* field[13] = edited */
  16,   /* field[16] = ephemeral */
  6,   /* field[6] = external */
  10,   /* field[10] = hidden */
  2,   /* field[2] = image */
  3,   /* field[3] = knock */
  4,   /* field[4] = lastRead */
  11,   /* field[11] = location */
  0,   /* field[0] = message_id */
  15,   /* field[15] = reaction */
  1,   /* field[1] = text */
};
static const ProtobufCIntRange generic_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor generic_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GenericMessage",
  "GenericMessage",
  "GenericMessage",
  "",
  sizeof(GenericMessage),
  17,
  generic_message__field_descriptors,
  generic_message__field_indices_by_name,
  2,  generic_message__number_ranges,
  (ProtobufCMessageInit) generic_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ephemeral__field_descriptors[6] =
{
  {
    "expire_after_millis",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Ephemeral, expire_after_millis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ephemeral, content_case),
    offsetof(Ephemeral, text),
    &text__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ephemeral, content_case),
    offsetof(Ephemeral, image),
    &image_asset__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "knock",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ephemeral, content_case),
    offsetof(Ephemeral, knock),
    &knock__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "asset",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ephemeral, content_case),
    offsetof(Ephemeral, asset),
    &asset__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ephemeral, content_case),
    offsetof(Ephemeral, location),
    &location__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ephemeral__field_indices_by_name[] = {
  4,   /* field[4] = asset */
  0,   /* field[0] = expire_after_millis */
  2,   /* field[2] = image */
  3,   /* field[3] = knock */
  5,   /* field[5] = location */
  1,   /* field[1] = text */
};
static const ProtobufCIntRange ephemeral__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ephemeral__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ephemeral",
  "Ephemeral",
  "Ephemeral",
  "",
  sizeof(Ephemeral),
  6,
  ephemeral__field_descriptors,
  ephemeral__field_indices_by_name,
  1,  ephemeral__number_ranges,
  (ProtobufCMessageInit) ephemeral__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor text__field_descriptors[3] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Text, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mention",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Text, n_mention),
    offsetof(Text, mention),
    &mention__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_preview",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Text, n_link_preview),
    offsetof(Text, link_preview),
    &link_preview__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned text__field_indices_by_name[] = {
  0,   /* field[0] = content */
  2,   /* field[2] = link_preview */
  1,   /* field[1] = mention */
};
static const ProtobufCIntRange text__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor text__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Text",
  "Text",
  "Text",
  "",
  sizeof(Text),
  3,
  text__field_descriptors,
  text__field_indices_by_name,
  1,  text__number_ranges,
  (ProtobufCMessageInit) text__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean knock__hot_knock__default_value = 0;
static const ProtobufCFieldDescriptor knock__field_descriptors[1] =
{
  {
    "hot_knock",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Knock, hot_knock),
    NULL,
    &knock__hot_knock__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned knock__field_indices_by_name[] = {
  0,   /* field[0] = hot_knock */
};
static const ProtobufCIntRange knock__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor knock__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Knock",
  "Knock",
  "Knock",
  "",
  sizeof(Knock),
  1,
  knock__field_descriptors,
  knock__field_indices_by_name,
  1,  knock__number_ranges,
  (ProtobufCMessageInit) knock__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor link_preview__field_descriptors[8] =
{
  {
    "url",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LinkPreview, url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url_offset",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LinkPreview, url_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "article",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LinkPreview, preview_case),
    offsetof(LinkPreview, article),
    &article__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "permanent_url",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LinkPreview, permanent_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LinkPreview, title),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "summary",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LinkPreview, summary),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LinkPreview, image),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tweet",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LinkPreview, meta_data_case),
    offsetof(LinkPreview, tweet),
    &tweet__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned link_preview__field_indices_by_name[] = {
  2,   /* field[2] = article */
  6,   /* field[6] = image */
  3,   /* field[3] = permanent_url */
  5,   /* field[5] = summary */
  4,   /* field[4] = title */
  7,   /* field[7] = tweet */
  0,   /* field[0] = url */
  1,   /* field[1] = url_offset */
};
static const ProtobufCIntRange link_preview__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor link_preview__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LinkPreview",
  "LinkPreview",
  "LinkPreview",
  "",
  sizeof(LinkPreview),
  8,
  link_preview__field_descriptors,
  link_preview__field_indices_by_name,
  2,  link_preview__number_ranges,
  (ProtobufCMessageInit) link_preview__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tweet__field_descriptors[2] =
{
  {
    "author",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tweet, author),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tweet, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tweet__field_indices_by_name[] = {
  0,   /* field[0] = author */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange tweet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tweet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Tweet",
  "Tweet",
  "Tweet",
  "",
  sizeof(Tweet),
  2,
  tweet__field_descriptors,
  tweet__field_indices_by_name,
  1,  tweet__number_ranges,
  (ProtobufCMessageInit) tweet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor article__field_descriptors[4] =
{
  {
    "permanent_url",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Article, permanent_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Article, title),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "summary",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Article, summary),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Article, image),
    &asset__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned article__field_indices_by_name[] = {
  3,   /* field[3] = image */
  0,   /* field[0] = permanent_url */
  2,   /* field[2] = summary */
  1,   /* field[1] = title */
};
static const ProtobufCIntRange article__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor article__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Article",
  "Article",
  "Article",
  "",
  sizeof(Article),
  4,
  article__field_descriptors,
  article__field_indices_by_name,
  1,  article__number_ranges,
  (ProtobufCMessageInit) article__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mention__field_descriptors[2] =
{
  {
    "user_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mention, user_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mention, user_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mention__field_indices_by_name[] = {
  0,   /* field[0] = user_id */
  1,   /* field[1] = user_name */
};
static const ProtobufCIntRange mention__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mention__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Mention",
  "Mention",
  "Mention",
  "",
  sizeof(Mention),
  2,
  mention__field_descriptors,
  mention__field_indices_by_name,
  1,  mention__number_ranges,
  (ProtobufCMessageInit) mention__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor last_read__field_descriptors[2] =
{
  {
    "conversation_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LastRead, conversation_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_read_timestamp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(LastRead, last_read_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned last_read__field_indices_by_name[] = {
  0,   /* field[0] = conversation_id */
  1,   /* field[1] = last_read_timestamp */
};
static const ProtobufCIntRange last_read__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor last_read__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LastRead",
  "LastRead",
  "LastRead",
  "",
  sizeof(LastRead),
  2,
  last_read__field_descriptors,
  last_read__field_indices_by_name,
  1,  last_read__number_ranges,
  (ProtobufCMessageInit) last_read__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cleared__field_descriptors[2] =
{
  {
    "conversation_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cleared, conversation_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cleared_timestamp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Cleared, cleared_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cleared__field_indices_by_name[] = {
  1,   /* field[1] = cleared_timestamp */
  0,   /* field[0] = conversation_id */
};
static const ProtobufCIntRange cleared__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cleared__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Cleared",
  "Cleared",
  "Cleared",
  "",
  sizeof(Cleared),
  2,
  cleared__field_descriptors,
  cleared__field_indices_by_name,
  1,  cleared__number_ranges,
  (ProtobufCMessageInit) cleared__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor message_hide__field_descriptors[2] =
{
  {
    "conversation_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MessageHide, conversation_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MessageHide, message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_hide__field_indices_by_name[] = {
  0,   /* field[0] = conversation_id */
  1,   /* field[1] = message_id */
};
static const ProtobufCIntRange message_hide__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor message_hide__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageHide",
  "MessageHide",
  "MessageHide",
  "",
  sizeof(MessageHide),
  2,
  message_hide__field_descriptors,
  message_hide__field_indices_by_name,
  1,  message_hide__number_ranges,
  (ProtobufCMessageInit) message_hide__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor message_delete__field_descriptors[1] =
{
  {
    "message_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MessageDelete, message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_delete__field_indices_by_name[] = {
  0,   /* field[0] = message_id */
};
static const ProtobufCIntRange message_delete__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor message_delete__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageDelete",
  "MessageDelete",
  "MessageDelete",
  "",
  sizeof(MessageDelete),
  1,
  message_delete__field_descriptors,
  message_delete__field_indices_by_name,
  1,  message_delete__number_ranges,
  (ProtobufCMessageInit) message_delete__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor message_edit__field_descriptors[2] =
{
  {
    "replacing_message_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MessageEdit, replacing_message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MessageEdit, content_case),
    offsetof(MessageEdit, text),
    &text__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_edit__field_indices_by_name[] = {
  0,   /* field[0] = replacing_message_id */
  1,   /* field[1] = text */
};
static const ProtobufCIntRange message_edit__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor message_edit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageEdit",
  "MessageEdit",
  "MessageEdit",
  "",
  sizeof(MessageEdit),
  2,
  message_edit__field_descriptors,
  message_edit__field_indices_by_name,
  1,  message_edit__number_ranges,
  (ProtobufCMessageInit) message_edit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue confirmation__type__enum_values_by_number[2] =
{
  { "DELIVERED", "CONFIRMATION__TYPE__DELIVERED", 0 },
  { "READ", "CONFIRMATION__TYPE__READ", 1 },
};
static const ProtobufCIntRange confirmation__type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex confirmation__type__enum_values_by_name[2] =
{
  { "DELIVERED", 0 },
  { "READ", 1 },
};
const ProtobufCEnumDescriptor confirmation__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Confirmation.Type",
  "Type",
  "Confirmation__Type",
  "",
  2,
  confirmation__type__enum_values_by_number,
  2,
  confirmation__type__enum_values_by_name,
  1,
  confirmation__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor confirmation__field_descriptors[3] =
{
  {
    "first_message_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Confirmation, first_message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Confirmation, type),
    &confirmation__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "more_message_ids",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Confirmation, n_more_message_ids),
    offsetof(Confirmation, more_message_ids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned confirmation__field_indices_by_name[] = {
  0,   /* field[0] = first_message_id */
  2,   /* field[2] = more_message_ids */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange confirmation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor confirmation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Confirmation",
  "Confirmation",
  "Confirmation",
  "",
  sizeof(Confirmation),
  3,
  confirmation__field_descriptors,
  confirmation__field_indices_by_name,
  1,  confirmation__number_ranges,
  (ProtobufCMessageInit) confirmation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor location__field_descriptors[4] =
{
  {
    "longitude",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Location, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Location, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Location, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zoom",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Location, has_zoom),
    offsetof(Location, zoom),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned location__field_indices_by_name[] = {
  1,   /* field[1] = latitude */
  0,   /* field[0] = longitude */
  2,   /* field[2] = name */
  3,   /* field[3] = zoom */
};
static const ProtobufCIntRange location__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor location__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Location",
  "Location",
  "Location",
  "",
  sizeof(Location),
  4,
  location__field_descriptors,
  location__field_indices_by_name,
  1,  location__number_ranges,
  (ProtobufCMessageInit) location__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor image_asset__field_descriptors[11] =
{
  {
    "tag",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ImageAsset, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ImageAsset, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ImageAsset, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "original_width",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ImageAsset, original_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "original_height",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ImageAsset, original_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mime_type",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ImageAsset, mime_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ImageAsset, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "otr_key",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ImageAsset, has_otr_key),
    offsetof(ImageAsset, otr_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_key",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ImageAsset, has_mac_key),
    offsetof(ImageAsset, mac_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ImageAsset, has_mac),
    offsetof(ImageAsset, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha256",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ImageAsset, has_sha256),
    offsetof(ImageAsset, sha256),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned image_asset__field_indices_by_name[] = {
  2,   /* field[2] = height */
  9,   /* field[9] = mac */
  8,   /* field[8] = mac_key */
  5,   /* field[5] = mime_type */
  4,   /* field[4] = original_height */
  3,   /* field[3] = original_width */
  7,   /* field[7] = otr_key */
  10,   /* field[10] = sha256 */
  6,   /* field[6] = size */
  0,   /* field[0] = tag */
  1,   /* field[1] = width */
};
static const ProtobufCIntRange image_asset__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor image_asset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ImageAsset",
  "ImageAsset",
  "ImageAsset",
  "",
  sizeof(ImageAsset),
  11,
  image_asset__field_descriptors,
  image_asset__field_indices_by_name,
  1,  image_asset__number_ranges,
  (ProtobufCMessageInit) image_asset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor asset__original__field_descriptors[8] =
{
  {
    "mime_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Asset__Original, mime_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Asset__Original, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Asset__Original, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Asset__Original, meta_data_case),
    offsetof(Asset__Original, image),
    &asset__image_meta_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Asset__Original, meta_data_case),
    offsetof(Asset__Original, video),
    &asset__video_meta_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Asset__Original, meta_data_case),
    offsetof(Asset__Original, audio),
    &asset__audio_meta_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Asset__Original, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "caption",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Asset__Original, caption),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__original__field_indices_by_name[] = {
  5,   /* field[5] = audio */
  7,   /* field[7] = caption */
  3,   /* field[3] = image */
  0,   /* field[0] = mime_type */
  2,   /* field[2] = name */
  1,   /* field[1] = size */
  6,   /* field[6] = source */
  4,   /* field[4] = video */
};
static const ProtobufCIntRange asset__original__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor asset__original__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset.Original",
  "Original",
  "Asset__Original",
  "",
  sizeof(Asset__Original),
  8,
  asset__original__field_descriptors,
  asset__original__field_indices_by_name,
  1,  asset__original__number_ranges,
  (ProtobufCMessageInit) asset__original__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor asset__preview__field_descriptors[4] =
{
  {
    "mime_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Asset__Preview, mime_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Asset__Preview, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Asset__Preview, remote),
    &asset__remote_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Asset__Preview, meta_data_case),
    offsetof(Asset__Preview, image),
    &asset__image_meta_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__preview__field_indices_by_name[] = {
  3,   /* field[3] = image */
  0,   /* field[0] = mime_type */
  2,   /* field[2] = remote */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange asset__preview__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor asset__preview__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset.Preview",
  "Preview",
  "Asset__Preview",
  "",
  sizeof(Asset__Preview),
  4,
  asset__preview__field_descriptors,
  asset__preview__field_indices_by_name,
  1,  asset__preview__number_ranges,
  (ProtobufCMessageInit) asset__preview__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor asset__image_meta_data__field_descriptors[3] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Asset__ImageMetaData, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Asset__ImageMetaData, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Asset__ImageMetaData, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__image_meta_data__field_indices_by_name[] = {
  1,   /* field[1] = height */
  2,   /* field[2] = tag */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange asset__image_meta_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor asset__image_meta_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset.ImageMetaData",
  "ImageMetaData",
  "Asset__ImageMetaData",
  "",
  sizeof(Asset__ImageMetaData),
  3,
  asset__image_meta_data__field_descriptors,
  asset__image_meta_data__field_indices_by_name,
  1,  asset__image_meta_data__number_ranges,
  (ProtobufCMessageInit) asset__image_meta_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor asset__video_meta_data__field_descriptors[3] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Asset__VideoMetaData, has_width),
    offsetof(Asset__VideoMetaData, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Asset__VideoMetaData, has_height),
    offsetof(Asset__VideoMetaData, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration_in_millis",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Asset__VideoMetaData, has_duration_in_millis),
    offsetof(Asset__VideoMetaData, duration_in_millis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__video_meta_data__field_indices_by_name[] = {
  2,   /* field[2] = duration_in_millis */
  1,   /* field[1] = height */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange asset__video_meta_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor asset__video_meta_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset.VideoMetaData",
  "VideoMetaData",
  "Asset__VideoMetaData",
  "",
  sizeof(Asset__VideoMetaData),
  3,
  asset__video_meta_data__field_descriptors,
  asset__video_meta_data__field_indices_by_name,
  1,  asset__video_meta_data__number_ranges,
  (ProtobufCMessageInit) asset__video_meta_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor asset__audio_meta_data__field_descriptors[2] =
{
  {
    "duration_in_millis",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Asset__AudioMetaData, has_duration_in_millis),
    offsetof(Asset__AudioMetaData, duration_in_millis),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normalized_loudness",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Asset__AudioMetaData, has_normalized_loudness),
    offsetof(Asset__AudioMetaData, normalized_loudness),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__audio_meta_data__field_indices_by_name[] = {
  0,   /* field[0] = duration_in_millis */
  1,   /* field[1] = normalized_loudness */
};
static const ProtobufCIntRange asset__audio_meta_data__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor asset__audio_meta_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset.AudioMetaData",
  "AudioMetaData",
  "Asset__AudioMetaData",
  "",
  sizeof(Asset__AudioMetaData),
  2,
  asset__audio_meta_data__field_descriptors,
  asset__audio_meta_data__field_indices_by_name,
  2,  asset__audio_meta_data__number_ranges,
  (ProtobufCMessageInit) asset__audio_meta_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor asset__remote_data__field_descriptors[5] =
{
  {
    "otr_key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Asset__RemoteData, otr_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha256",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Asset__RemoteData, sha256),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "asset_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Asset__RemoteData, asset_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "asset_token",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Asset__RemoteData, asset_token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encryption",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Asset__RemoteData, has_encryption),
    offsetof(Asset__RemoteData, encryption),
    &encryption_algorithm__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__remote_data__field_indices_by_name[] = {
  2,   /* field[2] = asset_id */
  3,   /* field[3] = asset_token */
  4,   /* field[4] = encryption */
  0,   /* field[0] = otr_key */
  1,   /* field[1] = sha256 */
};
static const ProtobufCIntRange asset__remote_data__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor asset__remote_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset.RemoteData",
  "RemoteData",
  "Asset__RemoteData",
  "",
  sizeof(Asset__RemoteData),
  5,
  asset__remote_data__field_descriptors,
  asset__remote_data__field_indices_by_name,
  2,  asset__remote_data__number_ranges,
  (ProtobufCMessageInit) asset__remote_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue asset__not_uploaded__enum_values_by_number[2] =
{
  { "CANCELLED", "ASSET__NOT_UPLOADED__CANCELLED", 0 },
  { "FAILED", "ASSET__NOT_UPLOADED__FAILED", 1 },
};
static const ProtobufCIntRange asset__not_uploaded__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex asset__not_uploaded__enum_values_by_name[2] =
{
  { "CANCELLED", 0 },
  { "FAILED", 1 },
};
const ProtobufCEnumDescriptor asset__not_uploaded__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Asset.NotUploaded",
  "NotUploaded",
  "Asset__NotUploaded",
  "",
  2,
  asset__not_uploaded__enum_values_by_number,
  2,
  asset__not_uploaded__enum_values_by_name,
  1,
  asset__not_uploaded__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor asset__field_descriptors[4] =
{
  {
    "original",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Asset, original),
    &asset__original__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "not_uploaded",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Asset, status_case),
    offsetof(Asset, not_uploaded),
    &asset__not_uploaded__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uploaded",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Asset, status_case),
    offsetof(Asset, uploaded),
    &asset__remote_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preview",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Asset, preview),
    &asset__preview__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned asset__field_indices_by_name[] = {
  1,   /* field[1] = not_uploaded */
  0,   /* field[0] = original */
  3,   /* field[3] = preview */
  2,   /* field[2] = uploaded */
};
static const ProtobufCIntRange asset__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor asset__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Asset",
  "Asset",
  "Asset",
  "",
  sizeof(Asset),
  4,
  asset__field_descriptors,
  asset__field_indices_by_name,
  2,  asset__number_ranges,
  (ProtobufCMessageInit) asset__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor external__field_descriptors[3] =
{
  {
    "otr_key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(External, otr_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha256",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(External, has_sha256),
    offsetof(External, sha256),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encryption",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(External, has_encryption),
    offsetof(External, encryption),
    &encryption_algorithm__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external__field_indices_by_name[] = {
  2,   /* field[2] = encryption */
  0,   /* field[0] = otr_key */
  1,   /* field[1] = sha256 */
};
static const ProtobufCIntRange external__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor external__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "External",
  "External",
  "External",
  "",
  sizeof(External),
  3,
  external__field_descriptors,
  external__field_indices_by_name,
  1,  external__number_ranges,
  (ProtobufCMessageInit) external__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reaction__field_descriptors[2] =
{
  {
    "emoji",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Reaction, emoji),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Reaction, message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reaction__field_indices_by_name[] = {
  0,   /* field[0] = emoji */
  1,   /* field[1] = message_id */
};
static const ProtobufCIntRange reaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor reaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Reaction",
  "Reaction",
  "Reaction",
  "",
  sizeof(Reaction),
  2,
  reaction__field_descriptors,
  reaction__field_indices_by_name,
  1,  reaction__number_ranges,
  (ProtobufCMessageInit) reaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor calling__field_descriptors[1] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Calling, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned calling__field_indices_by_name[] = {
  0,   /* field[0] = content */
};
static const ProtobufCIntRange calling__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor calling__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Calling",
  "Calling",
  "Calling",
  "",
  sizeof(Calling),
  1,
  calling__field_descriptors,
  calling__field_indices_by_name,
  1,  calling__number_ranges,
  (ProtobufCMessageInit) calling__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue client_action__enum_values_by_number[1] =
{
  { "RESET_SESSION", "CLIENT_ACTION__RESET_SESSION", 0 },
};
static const ProtobufCIntRange client_action__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex client_action__enum_values_by_name[1] =
{
  { "RESET_SESSION", 0 },
};
const ProtobufCEnumDescriptor client_action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientAction",
  "ClientAction",
  "ClientAction",
  "",
  1,
  client_action__enum_values_by_number,
  1,
  client_action__enum_values_by_name,
  1,
  client_action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue encryption_algorithm__enum_values_by_number[2] =
{
  { "AES_CBC", "ENCRYPTION_ALGORITHM__AES_CBC", 0 },
  { "AES_GCM", "ENCRYPTION_ALGORITHM__AES_GCM", 1 },
};
static const ProtobufCIntRange encryption_algorithm__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex encryption_algorithm__enum_values_by_name[2] =
{
  { "AES_CBC", 0 },
  { "AES_GCM", 1 },
};
const ProtobufCEnumDescriptor encryption_algorithm__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EncryptionAlgorithm",
  "EncryptionAlgorithm",
  "EncryptionAlgorithm",
  "",
  2,
  encryption_algorithm__enum_values_by_number,
  2,
  encryption_algorithm__enum_values_by_name,
  1,
  encryption_algorithm__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
